apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fake-aegis-prod
resources:
  - ../../base
configMapGenerator:
  - name: fake-aegis
    behavior: replace
    files:
      - index.html=index.html
generatorOptions:
  disableNameSuffixHash: true
